name: Publish

on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m build

      - run: |
          cp * /var/www/php/threadsnake